### ISSUE TITLE
Check failed on `all` field

### ISSUE THREAD

**Issue by pdegama** [albertito/spf#9]
my domain spf record is `v=spf1 mx ~all` and yahoo spf record is `v=spf1 ptr:yahoo.com ptr:yahoo.net ?all` it is fail on this line why, other mail server accept my mail and pass to spf check but, it lib fail?

https://github.com/albertito/spf/blob/3731c77a3e96a57212e32af95c22e37368df0807/spf.go#L385

**Comment by albertito** [comment]
Hi Parthka!

Unfortunately, I'll need a bit more information to understand why the check is failing: at least the IP address of the sender, and the domain in question.

You can also use some public checkers to verify your configuration, for example:

- https://mxtoolbox.com/SPF.aspx
- https://easydmarc.com/tools/spf-lookup
- https://www.learndmarc.com/

Also, how is Yahoo's spf record related to your problem?

Thank you!

**Comment by albertito** [comment]
I'm going to close this due to inactivity, but please reopen if you have a reply with more information as per the previous comment. Thank you!
